#ifndef CFG_H
#define CFG_H

#define CFG_PROFILE_PROFILEID 0U
#define CFG_PROFILE_STARTFREQCONST 1435388860U
#define CFG_PROFILE_IDLETIMECONST 700U
#define CFG_PROFILE_ADCSTARTTIMECONST 700U
#define CFG_PROFILE_RAMPENDTIME 2081U
#define CFG_PROFILE_FREQSLOPECONST 932U
#define CFG_PROFILE_NUMADCSAMPLES 256U
#define CFG_PROFILE_DIGOUTSAMPLERATE 30000U
#define CFG_PROFILE_RXGAIN 164U

#endif
